Task1
Aspirisha/au-softdes pull request #2
Opened 2016-09-24 21:14 UTC by Aspirisha

Task 1 full implementation

2016-10-04 09:56 UTC, yurii-litvinov requested changes
В целом я бы сказал, что это овердизайн, но для практики по проектированию это простительно :) Надо что-то сделать с системой сборки, всё должно складываться куда-нибудь в target. И написать ещё кучу комментариев.

2016-10-04 09:56 UTC, yurii-litvinov commented on README.md
> +3. Now shell is installed into $HOME/sdshell/ directory.
Зачем оно мне там? :) Желательно, чтобвы всё собиралось куда-нибудь в папку с проектом. Под виндой не работает, кстати.

2016-10-04 09:56 UTC, yurii-litvinov commented on cat/src/main/java/au/sdshell/tools/cat/CatTool.java
> +public class CatTool {
Нужны комментарии, к классам и к каждому public-методу, как минимум.

2016-10-04 09:56 UTC, yurii-litvinov commented on cat/src/main/java/au/sdshell/tools/cat/CatTool.java
> +
Две пустые строки подряд обычно не поощряются.

2016-10-04 09:56 UTC, yurii-litvinov commented on common/src/main/java/au/sdshell/common/Environment.java
> +                        break;
В Java принято оборачивать тела сложных операторов в {}, даже если там один оператор. Чтобы потом не забыть, а то может получиться
```java
if (prevWasEscape || quoteState)
    System.out.println("Ololo");
    break;
```

2016-10-04 09:56 UTC, yurii-litvinov commented on common/src/main/java/au/sdshell/common/Environment.java
> +                            charIsPartOfName(s.charAt(lastVarChar)); lastVarChar++);
Даже пустое тело помечается фигурными скобками, так:
```java
for (lastVarChar++; lastVarChar < s.length() &&
    charIsPartOfName(s.charAt(lastVarChar)); lastVarChar++) {
}
```
Резко повышает читаемость, по идее.

2016-10-04 09:56 UTC, yurii-litvinov commented on common/src/main/java/au/sdshell/common/FileResolver.java
> +        return false;
Мне кажется, это можно проще и короче записать через anyMatch.

2016-10-04 09:56 UTC, yurii-litvinov commented on driver/src/main/java/au/sdshell/driver/Piper.java
> +            }
"Проглатывание" исключений огорчит любой статический анализатор.

2016-10-04 09:56 UTC, yurii-litvinov commented on driver/src/main/java/au/sdshell/driver/command/AssignCommand.java
> +    String value;
package-поля --- это почти как public-поля, не надо их использовать (если только они final и тип немутабелен, как тут).

2016-10-04 22:54 UTC, Aspirisha commented on driver/src/main/java/au/sdshell/driver/command/AssignCommand.java
> +    String value;
И правда, стоило бы сделать final.

2016-10-16 11:06 UTC, yurii-litvinov approved these changes

2016-10-16 11:06 UTC, merged