Software Design; Gorbunov; Task 3
Aspirisha/au-softdes pull request #5
Opened 2016-12-08 19:35 UTC by egorbunov

Here we go.

Dear Andy. Thank you for such a great and useful project, however I've decided that two more commands (`ls` and `cd`) are unavoidable in any great command shell like yours.

What I like about your architecture:

* Separate subprojects for every command, which makes "builtin" commands equal to external commands. So the only thing I've done to add `ls` was adding new subproject

What I think is not so cool:

* Commands, which modify CLI context somehow are handled differently (I mean usual commands like exit, not assign) and this difference is even appears in parser. I agree with that this commands need a special treatment, but parser can be unified for them all. Because of this I had to change parser to handle `cd` command (however, another way was to unpack `ToolCommand` later outside parser, but that is not so cool too). I think that the better way is to decide which command is `ToolCommand` and which is not later, after parsing.

2016-12-12 11:40 UTC, yurii-litvinov requested changes
Доделайте, пожалуйста.

2016-12-12 11:40 UTC, yurii-litvinov commented on driver/src/main/java/au/sdshell/driver/command/CDCommand.java
> +public class CDCommand {
Нужны более содержательные комментарии.

2016-12-12 11:40 UTC, yurii-litvinov commented on ls/src/main/java/au/sdshell/tools/ls/LSTool.java
> +public class LSTool {
Тут тоже, самому классу нужны комментарии.

2016-12-12 11:40 UTC, yurii-litvinov commented on ls/src/main/java/au/sdshell/tools/ls/LSTool.java
> +            });
По-хорошему, ls должна принимать опциональный аргумент, чтобы работало что-то вроде ls /usr/bin

2016-12-14 10:46 UTC, egorbunov commented
Поправил!

2016-12-18 14:52 UTC, yurii-litvinov approved these changes

2017-02-10 21:17 UTC, merged